version: '3.3'
services:
    db:
        image: mysql:latest
        container_name: app-mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: app-phpmyadmin
        links:
            - "db:db"
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: root
        restart: always
        ports:
            - "8080:80"
        volumes:
            - "/sessions"
    php:
        build: ./php-fpm
        container_name: app-php
        ports:
            - "9000:9001"
        volumes:
            - ./src:/var/www/
            - ./src/app/var/log:/var/www/var/log
        links:
            - db
        extra_hosts:
            - "docker.host:127.0.0.1"
    nginx:
        build: ./nginx
        container_name: app-nginx
        ports:
            - "88:80"
        links:
            - php
        volumes:
            - ./logs/nginx:/var/log/nginx
            - ./src:/var/www/src
    elk:
        image: willdurand/elk
        container_name: app-elk
        ports:
            - "81:80"
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
            - ./src/app/var/log:/var/www/var/log
            - ./logs/nginx:/var/log/nginx

    front:
      image: nginx:latest
      container_name: app-angular 
      ports:
        - "80:80"
      volumes:
        - ./front:/var/www/html
        - ./angular/site.conf:/etc/nginx/conf.d/default.conf

    node:
      image: node:latest        

